### ISSUE TITLE
Develop an SDK strategy

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/meta#1]
The current scope of work specifies the development of an SDK as follows:

```quote
A software development kit (SDK) is a suite of pre-packaged tools that make a given
project easy to work with. We propose to provide an SDK that makes certain usage
patterns of the PDC API easily available in a commonly-used programming language
(probably Python, possibly Javascript). This will be an effective way to smooth the
path for technical partners (see item (2)) who want to exchange data with or query
the PDC.
```

This issue is not to capture the work of actually developing that SDK, but rather to identify the correct strategy for creating, deploying, and maintaining that SDK.

The result of this issue should be a proposed implementation plan that the PDC development team is comfortable with.

**Comment by slifty** [comment]
## Decision 1: Custom vs Generated

We have an [openapi specification](https://github.com/PhilanthropyDataCommons/service/blob/main/src/openapi.json) already.  There are existing tools out there which will generate client code (sdks) for a whole slew of languages.   For example: [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) and [swagger-js](https://github.com/swagger-api/swagger-js).

**Proposal:** We should NOT create any custom sdks by hand and should instead leverage those existing tools.

**Comment by slifty** [comment]
Within the "generated client" universe I've found 2.5 approaches...

## A: Runtime clients

Runtime clients are libraries themselves that consume a swagger spec to configure a client at runtime.  (e.g. [swagger-js](https://github.com/swagger-api/swagger-js)).

**Pros**
1. We would not need to update our CI to generate client code artifacts.
2. We would not need to publish or maintaining any sdk code.
3. Adding support for new languages would just be a matter of researching and providing documentation on how to configure a given client.

**Cons**
1. Support for any given language depends on whether someone has built a runtime client for that language, and the quality of their implementation.  For instance javascript seems to have a very robust runtime client, [python's equivalent](https://github.com/digium/swagger-py) has not been updated in six years.
2. We are reliant on third parties for maintaining quality of the user experience.  The tooling for working with the PDC API represents a critical piece of our relationship with technical PDC users.  If the tools available are hard to configure, buggy, or simply unpleasant to use then that negative experience would have consequences for the PDC.

**Neutrals**
1. We might want to write at least SOME kinds of tests to ensure that our openapi specification works properly for libraries we recommend.
2. We will need to think through how this would work against API versioning (e.g. we would probably ask users to lock in a version of our swagger spec rather than dynamically load the one served, since otherwise their clients would change in production as we updated our deployments.)

## B: Client generators (where we publish the result)

Client generators consume a swagger spec to create actual code for libraries in various languages. It looks like the best in class right now is [swagger codegen](https://github.com/swagger-api/swagger-codegen).

**Pros**
1. We have full control over what ultimately gets generated and published.
2. Swagger codegen supports a [ton of languages](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages) out of the box.
3. Swagger codegen appears to *also* generate automated tests (at least for python and typescript, which are the two I tried so far).
4. We have the power to fix bugs, since we're the ones actually publishing.
5. We get to leverage things like dependabots to announce / distribute new versions of our API.

**Cons**
1. We have figure out how to incorporate SDK generation into our CI / build steps.

**Neutrals**
1. Do we trust automatically generated automated tests or would we also want some of our own?
2. If something goes wrong with a generated client that we have published we are responsible for fixing it. I'm putting this in neutral because to some extent I think that we would be functionally responsible for helping to fix *any* kind of PDC client code, even if we didn't publish it.
3. API versioning + SDK versioning feels more natural with this approach, but it also will still require thought and implementation.

## C: Client generators (where the API user generates the client for themselves)

This would just mean we point people in the direction of something like swagger codegen, and maybe provide some examples, but users have to generate the clients themselves.

**Pros**
1. We get the benefits of Swagger codegen's breadth without the listed cons.

**Cons**
1. Similar to (A), we are in a position where we are responsible for supporting but now lack the ability to make certain types of fixes.
2. Third parties become in the business of having to rebuild their clients whenever we update our API (without the benefit of dependabot)

---

I should note that the answer could (should!) be more than one of the above.  For instance, we might decide to generate and publish a typescript library, but would still want to help users know how they could generate their own clients in the language of their choice.

**Comment by slifty** [comment]
I have to step away for a bit to exercise and eat lunch, but will be writing down some thoughts around CI and implementation of 2B (generated clients where we publish the result).

**Comment by slifty** [comment]
## Decision 3-2B : CI / Deployment

If we are going to use an sdk generator we're going to need to decide when and how to do that generation.  Rather than listing out a series of detailed options I'm actually going to just write a proposal here, and if we decide to go with 2B we can flesh it out.

**Proposal:** an sdk repository responsible for generating, tracking, building, releasing, and publishing any SDK(s).

To do this we would need to...

1. Update the `service` repository to publish a versioned release swagger specification as a release artifact.

2. Create an `sdk` repository that has CI to generate, push, build, release, and publish the corresponding SDK(s) whenever there is a newly published swagger specification.  In my mind we would have one SDK release for every published API version.

3. Finalize, document, and implement an API versioning plan.  I'd like to explore this in more detail outside of this issue.

The service repository scope is not changed (we should probably be publishing the api specification as a release artifact anyway).  I believe this would involve a dispatch event similar to the pattern we use for `deploy`, though the builds should only happen when the api version is updated (as opposed to every change to `service` which is how `deploy` works)

**Comment by jasonaowen** [comment]
I agree with 1 and 2B!

> Update the service repository to publish a versioned release swagger specification as a release artifact.

Can you say more about where/how this would be published?

One alternative to having a separate repo is to make building/publishing SDK(s) be an additional step in the `service` repo; it might be worth figuring out pros/cons for each option.

> Finalize, document, and implement an API versioning plan. I'd like to explore this in more detail outside of this issue.

+1 - this is a conversation we need to have!

**Comment by slifty** [comment]
> One alternative to having a separate repo is to make building/publishing SDK(s) be an additional step in the service repo; it might be worth figuring out pros/cons for each option.

Yes!  I'll write out some pros and cons next week

**Comment by slifty** [comment]
## Decision 3: How to build and publish the SDK

We've landed on 2B (we'll be using code generators to create the SDK).  Now we get to decide the process for invoking those generators and ultimately publishing the resulting SDKs.

The steps are:

1. Updating the version of the API
2. Invoking the generators to create SDK artifacts
3. Converting those SDK artifacts into packages (this may not be needed but I'm mentioning it in case it is)
4. Publishing the packages to appropriate package repositories (e.g. pip, github, npm).

There are a few ways to actually implement these steps, and that's what the next decision needs to involve.

### A: Manual Implementation

We could do these steps manually / as part of deciding to release a new version of the API.  This would be augmented with scripts to help (e.g. `npm run sdk:build` and `npm run sdk:publish`).  These scripts could live in the `service` directory or in an `sdk` directory.

**Pros**
1. Provides the opportunity for a human to ensure that everything was built properly and looks reasonable.
2. If something goes wrong the human would be able to immediately start working to address the situation.
3. This might involve a little less infrastructure.

**Cons**
1. This leaves the most room for human error.
2. This costs ongoing developer time.

### B: GitHub Actions within the `service` repository

The service repository is where the API is defined, and in turn it is where API versioning is managed.  The SDK is being generated based on the OpenAPI spect that is ultimately defined in the service repository.

We could update the CI in the service repository to leverage GitHub automatically build and publish sdk artifacts.

**Pros**
1. Builds can be triggered by pushes without requiring cross-repo communication.

**Cons**
1. We would either need to decide to never support template customization OR decide to add SDK customized template files in the `service` repository.  The latter feels like it would be conflating scope (what if we want to lint those templates?  If we want dev tooling for local iteration on templates we will need to add a java dependency to the development environment of the service repository, etc)

2. Published packages would not be as intuitively aligned with our repository name (e.g. `@philanthropy-data-commons/sdk` resolving to a repository named `sdk` is more intuitive than resolving to a repository named `service`.

**Considerations**
1. Do we want to version control the generated SDKs (e.g. should folks be able to see how the versions changed over time with the ability to view diffs?) If so, our `service` repository would essentially become a monorepo that contains both an API service as well as a series of SDK package code bases.

### B: Automation within a new `sdk` repository

We could have an `sdk` repository that is responsible for encapsulating the configuration, customization, and generated code related to our sdk.  I imagine this would involve updating our service CI to explicitly publish versions of the swagger specification document as versioned "releases" -- and then having CI configued in an `sdk` repository to build and publish new versions of the SDK whenever there is a new OpenAPI version released by the `service` repository.

**Pros**
1. A single git history for tracking changes to generation configuration, templates, and other SDK-related files that we want version control for.

2. A single git repository for issue management related to the SDK.

3. If we want to expose sdk code diffs / version control the sdk products this would create a good space for that concept.

4. Clear delineation of responsibilities between the `sdk` and `service` repositories (if it relates to api implementation it is in the service repository; if it relates to sdk implementation it is in the sdk repository)

5. Decisions related to SDK management, generation, etc will have no impact on the `service` repository.  For example: we don't need to worry about changes to the SDK configuration / customization triggering new service builds and deployments; we won't have to worry about the development stack behind the SDK having conflicts with the service stack.

6. Clear delineation between published resources in the `service` and `sdk`. For instance we might find it valuable to publish the service specification as a github artifact (which is USED by the sdk, but is not itself part of the SDK / is actually part of the service)

**Cons**
1. It's more complicated to set up a pipeline where new versions of the API invoke new versions of the SDK.

----------------

I personally think that the `sdk` represents a distinct client -- similar to how the `front-end` represents a distinct client.  And though the sdk is dependent on changes in `service` those dependencies are best managed through explicit references rather than coupled code bases.

For these reasons I'd like to float 2B as the proposed path.

**Comment by slifty** [comment]
We (@jasonaowen @reefdog @bickelj) talked through this have decided that for the short term...

1. We do not really expect there to be meaningful code artifacts related to SDK (outside of CI integration)
2. the overhead of cross-repo triggers is large and not well supported by github right now.

for these reasons we're going to go with `3B`.  This doesn't preclude us from some day creating an `sdk` repository at some later date of course (e.g. if we decide we want to start customizing templates).

I'm going to create a series of SDK related issues over in the `service` repository now.
