### ISSUE TITLE
Establish an implementation strategy for "bulk" upload via CSV template

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/meta#128]
We want to allow users to add data to the system by uploading a specifically formatted CSV containing proposal data.

There are a few ways to implement this from an architecture perspective; this issue is dedicated to picking one to pursue.

**Comment by slifty** [comment]
## Some Questions

1. Where does the API endpoint live for CSV upload
2. Where does the business logic that processes the CSV live
3. Should the CSV processor function as an API client.

## Proposal

### Step 1: Uploading the CSV
it'd be pretty weird to have the CSV upload happen via a different service than the client facing API; I think that we are going to want a `service` endpoint that allows users to register bulk uploads.  The CSV would then be posted directly by the client to an S3 destination.

The flow might look like this:

```mermaid
sequenceDiagram
    Client->>Service: Register CSV Upload
    activate Service
    Service->>S3: Generate presigned post
    Service->>Client: S3 protocol presigned post for CSV upload
    deactivate Service
    activate Client
    Client->>S3: Upload S3 result
    Client->>Service: Register completed upload
    deactivate Client
```

For the `service` this would involve the creation of a new entity type -- something like `BulkUpload`

**Comment by reefdog** [comment]
+1 to all of the above!

An MVP feature related to "Ability to see a list of CSV files uploaded by a given user" is the ability for the user to check processing status. I imagine upload will be blocking and we won't "let" the user leave the page while it's happening, but then parsing/processing will be queued/non-blocking. Users will be told something like "great, check back later!" and if they check back they'll see either "still processing" or "done". Which status I also assume will be reported via a polling/status endpoint, not something like a live WebSocket.

Do you want to capture that here or as a separate task?

**Comment by slifty** [comment]
Here's good (and you've captured it I *think* for the purposes of this issue; I plan to end this by breaking the issue into a bunch of actual "task" issues in the appropriate repositories related to implementation plan)

**Comment by slifty** [comment]
All righty -- I'm gonna make some issues based on the thinking in this thread and then mark it as complete.
