### ISSUE TITLE
Understand and document the targeted user experience for "public access" of PDC data and interfaces

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/meta#130]

**Comment by reefdog** [comment]
Until we _create_ a need by describing new features, we only have these use cases for public data, both of whom are for "Nina" (the changemaker executive):

- https://github.com/PhilanthropyDataCommons/meta/issues/7
  - The dual purpose of the feature is "let prospective users see if their org is in the dataset" (with the assumption that they will then request an account) and also "demonstrate the breadth of data in the PDC in a low-commitment way" (i.e. to drive-by visitors, prospective users/stakeholders, etc.).
- https://github.com/PhilanthropyDataCommons/meta/issues/8
  - This "claim an org while requesting an account" flow still requires admin approval (see [meta/#9](https://github.com/PhilanthropyDataCommons/meta/issues/9) and [meta/#12](https://github.com/PhilanthropyDataCommons/meta/issues/12)), but technically means we need to expose some limited org data so the prospective user can select an existing org from a list while registering. This process would probably be linked to the above view — so users looking at the dataset could choose to "claim this org" and be fed into the account request flow.)

**Comment by slifty** [comment]
@reefdog we should make some issues for this! I can take on the `service` issues but would rely on you for the `front-end` ones.

**Comment by reefdog** [comment]
I should create some issues!

**Comment by reefdog** [comment]
Will do. In current phase, we'll only deliver https://github.com/PhilanthropyDataCommons/meta/issues/7. I'll create issues.
