### ISSUE TITLE
Record demo video of bulk upload

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/meta#132]

**Comment by reefdog** [comment]
Here's the Bulk Upload tour, feedback welcome! @jmergy @kfogel

I recorded this before watching [Dan's SDK video](https://github.com/PhilanthropyDataCommons/meta/issues/134#issuecomment-1964453421)… and hoo boy, does Dan's have substantially better (and more) production value! Wow. In particular, my audio setup is clearly worse, but also the overall editing of his is fantastic. I hope this "live, straight-through demonstration" is acceptable… but if not, and it needs to have real "post on the website" marketing-level quality, let me know.

https://github.com/PhilanthropyDataCommons/meta/assets/4731/ecb7facb-046a-406a-b96c-80fd93510480

**Comment by jmergy** [comment]
@reefdog this is great. Only possible add would be to say specifically the bulk upload is looking for those base field keys in the first row of the file. Of course, it says it in the upload page text and anyone doing this would know that has to be in-place. But, that would be the only mod here if you were to re-record for some reason. I don't think you need to. Voice is great.
