### ISSUE TITLE
Record demo video of UI/UX improvements

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/meta#133]

**Comment by reefdog** [comment]
All we really have to show for UI/UX improvements is the new navbar links. :/ As with the other video, this pales in comparison to @slifty's production values in https://github.com/PhilanthropyDataCommons/meta/issues/134#issuecomment-1964453421.

https://github.com/PhilanthropyDataCommons/meta/assets/4731/4c8e415b-8a58-4948-a428-0b8615a20dd1

**Comment by slifty** [comment]
I don't get a vote but this is great!

**Comment by jmergy** [comment]
@reefdog Excellent! 

I think we are okay but also wanted to mention something (and I always forget!) but recording vids on systems with real data or even doing demos with real data is just something to consider. In this vid, we didn't drop into any details so I think we are okay. Exposing the name, EIN, city, state, country is pretty generic. 

It's just something to consider specifically around this data and organization or proposal data - if we are going to post vids with public access/viewing.

**Comment by reefdog** [comment]
@jmergy Ah that's a good note! I have studiously tried to avoid leaking any real org/proposal data, but in my enthusiasm to show this on the real production domain, I forgot about that. Thanks for the reminder.

**Comment by jmergy** [comment]
@reefdog You did great but just something I didn't remind and I always forget until after I do! Thanks!
