### ISSUE TITLE
Add tasks for filtering proposals to those associated with MY bulk uploads

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/meta#142]

**Comment by reefdog** [comment]
- https://github.com/PhilanthropyDataCommons/front-end/issues/620
- https://github.com/PhilanthropyDataCommons/front-end/issues/621
- https://github.com/PhilanthropyDataCommons/front-end/issues/622
- https://github.com/PhilanthropyDataCommons/front-end/issues/623

**Comment by slifty** [comment]
@reefdog asked for this to be re-opened to also create some issues (or edit the existing ones) to represent non-bulk-upload proposals as well (e.g. someone created a proposal via API, that should appear too).

**Comment by reefdog** [comment]
Aaaand done.
