### ISSUE TITLE
Generate some fake data to replace the current pilot data

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/meta#143]

**Comment by reefdog** [comment]
I'm pretty sure @jmergy is tackling this one, so I'm reassigning.

**Comment by jmergy** [comment]
Hey - I got them in via Bulk Upload. @reefdog @slifty 
![image](https://github.com/PhilanthropyDataCommons/meta/assets/2380410/53e9cf25-1b0f-4ae7-8fee-4390d6bd6692)

**Comment by slifty** [comment]
Hooray!!  Closing as complete.
