### ISSUE TITLE
Review the User Stories project for Phase 5

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/meta#151]
This project has a bunch of user stories: https://github.com/orgs/PhilanthropyDataCommons/projects/4

Let's go through them and make sure any that are relevant in Phase 5 are marked as "Todo" and any that are missing for phase 5 are added (and marked as "Todo")

**Comment by kfogel** [comment]
FYI, edit title and initial description to say "Phase 5" instead of "Phase 3", to match our agreed-on New World Order.

**Comment by slifty** [comment]
Karl did this!  We decided to archive the whole thing and make a new "API user stories" that is more focused on API functionality, rather than front-end functionality.

https://github.com/orgs/PhilanthropyDataCommons/projects/12/views/1
